# Generated by Django 3.2.16 on 2022-12-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20221225_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorie_image',
        ),
    ]
