# Generated by Django 3.2.16 on 2023-01-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_post_categorie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='exerpt',
        ),
    ]
