# Generated by Django 3.2.16 on 2023-01-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_rename_body_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
